version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install pipenv
            pipenv install --dev --system
      - restore_cache:
           keys:
              - v1-dependencies-{{ .Branch }}-{{ checksum "setup.py" }}
              - v1-dependencies-{{ .Branch }}-
              - v1-dependencies-
      - run:
          name: initialize submodule
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: run test
          command: |
            . venv/bin/activate
            mkdir -p test-reports
            pytest tests -k 'not gpu'
