name: relighter_real
model_type: PyramidRelightingModel
layers: 1
scale_factor: 2
interp_mode: bicubic
scale: 3
num_gpu: 2  # set num_gpu: 0 for cpu mode
gpu_id: "0"
manual_seed: 10
rank: 0
world_size: 1
parallel: True


datasets:
  train:
    name: AdobeMultiIllumination
    type: AdobeMultiIlluminationOnetoOneDataset
    dataroot: ./data/MultiIllumination/train
    input_dir: 0
    gt_dir: 17

    gt_size: 992
    use_flip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 2
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: AdobeMultiIllumination
    type: AdobeMultiIlluminationOnetoOneDataset
    dataroot: ./data/MultiIllumination/test
    input_dir:  0
    gt_dir: 17


# network structures
network_g:
  type: "Relighter"


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  total_iter: 120000
  warmup_iter: -1  # no warm up
  decay_freq: 120000 # no decay
  gamma: 0.5

  # losses
  pixel_opt:
      type: L1Loss
      loss_weight: 1.0
      reduction: mean
  grad_opt:
      type: GradientLoss
      loss_weight: 1
      reduction: mean

# validation settings
val:
  val_freq: !!float 1000
  save_img: false
  save_tb_img: false
  save_tb_select: 
    - Image333
    - Image334
    - Image315
    - Image317

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
  best_metrics: 
    name: psnr
    greater: True
    val: !!float 0
    iter: !!int 0
  best_metrics2: 
    name: ssim
    greater: True
    val: !!float 0
    iter: !!int 0

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1000
  use_tb_logger: True

